/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData bebidas = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verduras = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresco = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sandalla_Mujer = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData celular = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camara = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bota_Mujer = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sandalla_playa = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pollo = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pescado = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anillo = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camas = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cortinas = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teclado = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maletin = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plato = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bebidasAlc = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agua = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruta = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torta = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pan = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audifono1 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audifono2 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steam = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vestido = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casaca = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polo = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData falda = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData short = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carne1 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carne2 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData higiene = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abrrote = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pantalon = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playera = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polo_1 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulsera = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reloj = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perfume = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cepillo_pelo = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lavadoras = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData televisor = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cosina = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData licuadora = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ollaArrz = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frish = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frish2 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData batidora = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin2 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plancha = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gato = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perro = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pan2 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alitas = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pi_a = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salchicha = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData choclo = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eschabeche = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golosinas = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pan3 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolsas_plasticas = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sandallas_verano = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sandalla_verano_tacos = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData botas_media_canilla = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData olla_arrozera = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aretes = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aretes_largos = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joyeria = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anillo_de_bolas = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData novia_anillos = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vinos = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bebidas_energisantes = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paneton = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jugos_de_fruta = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collares = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perfume_mujeres = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData limpia_vidrios = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData limpia_vidrios2 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arete_cortos = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brazalete = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collar_de_perlas = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collar_cruz = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collar__largo = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulsera_1 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vodka = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coctel = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData champan = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bebidas_alcoholicas = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData botella_agua = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glasses = IconData(0xf530, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xf6be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xf6d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carrot = IconData(0xf787, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_cheers = IconData(0xf79f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guitar = IconData(0xf7a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mug_hot = IconData(0xf7b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheese = IconData(0xf7ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xf805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
